### ISSUE TITLE
junit reports not shown when two phase are ran by the same client

### ISSUE THREAD

**Issue by adrianoalmeida7** [caelum/integra#96]
When the same client runs two phases (say, integration-1 and integration-3), it's showing only the junit reports from the last ran phase.

**Comment by guilhermesilveira** [comment]
the CopyFilesPlugin should be executed in a "after command" basis, not "after phase"

**Comment by guilhermesilveira** [comment]
closing... another issue already says that this should be not a plugin but part of the program itself
